"""Heatprint core: weather-corrected heating analytics, pure Python (see docs/METHODS.md).

The package has no runtime dependencies (ADR 0002) and no Home Assistant imports
(ADR 0001). It is nested under ``custom_components/heatprint/`` so HACS can ship
it; imports stay ``from heatprint_core import ...``. The main entry points are
re-exported here.
"""

from __future__ import annotations

from .analysis import (
    InsufficientDataError,
    compare_periods,
    fit_signature,
    forecast_season,
    measure_effect,
    normalized_consumption,
    saving_between,
)
from .cost import billed_amount, generator_cost, hourly_cost, space_share_of_cost
from .dhw import estimate_baseline, split_dhw
from .flags import Flag
from .heat import carrier_to_heat, cop_day
from .importers import CsvInspection, inspect_readings_csv, parse_readings_csv
from .methods import compute_all, compute_day, preset, t_eff, tac_series
from .models import (
    CarrierInput,
    CarrierUnit,
    ClassicParams,
    Climatology,
    Comparison,
    Conversion,
    ConversionMode,
    DailyEnergy,
    DailyRecord,
    DailyRoomRecord,
    DailyWeather,
    DemandKind,
    DhwConfig,
    DhwMode,
    EmitterKind,
    Forecast,
    Generator,
    GeneratorKind,
    HouseParams,
    Measure,
    MeasureCategory,
    MethodConfig,
    PblParams,
    Period,
    PriceMode,
    Provider,
    Role,
    Room,
    RoomSignatureFit,
    Season,
    SeasonConfig,
    SignatureFit,
    Site,
    WeatherSourceConfig,
)
from .pipeline import build_daily_records, estimate_baselines
from .readings import readings_to_daily
from .rooms import (
    RoomDayInput,
    allocate_day,
    allocate_period,
    apply_room_not_fitted,
    daily_demand_integral,
    fit_room_signature,
    indicative_ua_w_per_k,
    room_weight,
)
from .season import season_for, season_window
from .weather import (
    KnmiClient,
    OpenMeteoClient,
    WeatherProvider,
    build_climatology,
    merge_weather,
    parse_knmi_daggegevens,
    parse_open_meteo_hourly,
    remaining_season_dd,
)

__version__ = "0.2.4"

__all__ = [
    "CarrierInput",
    "CarrierUnit",
    "ClassicParams",
    "Climatology",
    "Comparison",
    "Conversion",
    "ConversionMode",
    "CsvInspection",
    "DailyEnergy",
    "DailyRecord",
    "DailyRoomRecord",
    "DailyWeather",
    "DemandKind",
    "DhwConfig",
    "DhwMode",
    "EmitterKind",
    "Flag",
    "Forecast",
    "Generator",
    "GeneratorKind",
    "HouseParams",
    "InsufficientDataError",
    "KnmiClient",
    "Measure",
    "MeasureCategory",
    "MethodConfig",
    "OpenMeteoClient",
    "PblParams",
    "Period",
    "PriceMode",
    "Provider",
    "Role",
    "Room",
    "RoomDayInput",
    "RoomSignatureFit",
    "Season",
    "SeasonConfig",
    "SignatureFit",
    "Site",
    "WeatherProvider",
    "WeatherSourceConfig",
    "__version__",
    "allocate_day",
    "allocate_period",
    "apply_room_not_fitted",
    "billed_amount",
    "build_climatology",
    "build_daily_records",
    "carrier_to_heat",
    "compare_periods",
    "compute_all",
    "compute_day",
    "cop_day",
    "daily_demand_integral",
    "estimate_baseline",
    "estimate_baselines",
    "fit_room_signature",
    "fit_signature",
    "forecast_season",
    "generator_cost",
    "hourly_cost",
    "indicative_ua_w_per_k",
    "inspect_readings_csv",
    "measure_effect",
    "merge_weather",
    "normalized_consumption",
    "parse_knmi_daggegevens",
    "parse_open_meteo_hourly",
    "parse_readings_csv",
    "preset",
    "readings_to_daily",
    "remaining_season_dd",
    "room_weight",
    "saving_between",
    "season_for",
    "season_window",
    "space_share_of_cost",
    "split_dhw",
    "t_eff",
    "tac_series",
]
